import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./GUI/navbarTop";
import SocialIcons from "./GUI/socialIcons";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className="bg-gradient-to-r from-gray-800 from-10% via-blue-950 via-30% to-gray-900 to-90%">
        <SocialIcons></SocialIcons>
        <Navbar></Navbar>
        {children}
      </body>
    </html>
  );
}
