import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./GUI/navbarTop";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className="bg-gradient-to-b from-[#E0F7FA] to-[#2C3E50] min-h-screen">
        <div className="flex flex-col items-center justify-center min-h-screen">
          <Navbar></Navbar>
          {children}
        </div>
      </body>
    </html>
  );
}
