export const dataProject = [
  {
    id: 1,
    title: "Gestion de stock",
    description: "Solución integral para gestionar inventario, ventas y compras en distribuidoras de bebidas.",
    images: [
      "/projects/gestion-de-stock/gestion-de-stock-inicio.png",
      "/projects/gestion-de-stock/gestion-de-stock-login.png",
      "/projects/gestion-de-stock/gestion-de-stock-dashboard.png",
    ],
    demo: "",
    github: "https://github.com/nicog33b/distribuidora-app-gestion-de-stock-nextjs-boostrap",
    tags: [
      "JavaScript",
      "API",
      "CSS",
      "Next.js",
      "React",
      "Tailwind CSS",
      "Chart.js",
      "SweetAlert2",
      "Moment.js",
    ],
  },
  {
    id: 2,
    title: "www.kuberalabs.com",
    description: "Plataforma que ofrece software de alta calidad y soporte tecnológico confiable.",
    images: [
      "/projects/kuberalabs/main.png",
      "/projects/kuberalabs/dates.png",
      "/projects/kuberalabs/whatwedo.png",
      "/projects/kuberalabs/services.png",
      "/projects/kuberalabs/contact-footer.png",
    ],
    demo: "www.kuberalabs.com",
    github: "",
    tags: [
      "Next.js",
      "React",
      "EmailJS",
      "SplideJS",
      "AOS",
      "React Icons",
      "React Phone Input",
      "React Slick",
      "Slick Carousel",
      "SweetAlert2",
      "Tailwind CSS",
      "TypeScript",
    ],
  },
  {
    id: 3,
    title: "SonoroApp",
    description: "App web musical para personas mayores, utilizando la API de Spotify.",
    images: [
      "/projects/sonoro/main.png",
      "/projects/sonoro/radios.png",
      "/projects/sonoro/search.png",
    ],
    demo: "https://sonoro2.vercel.app/",
    github: "https://github.com/walterlarrea/sonoro2",
    tags: ["Next.js", "React.js", "TailwindCSS", "Spotify API & Auth", "API Rest"],
  },
  {
    id: 4,
    title: "E-commerce Solesdesign",
    description: "Plataforma de e-commerce moderna y optimizada para una experiencia de usuario excepcional.",
    images: [
      "/projects/solesdesign/main.png",
      "/projects/solesdesign/tienda.png",
      "/projects/solesdesign/productReview.png",
      "/projects/solesdesign/carrito.png",
    ],
    demo: "",
    github: "https://github.com/nicog33b/ecommerce-solesdesign-tailwind-nextjs-mercadopago",
    tags: [
      "Next.js",
      "React",
      "TailwindCSS",
      "MercadoPago SDK",
      "React Slick",
      "SweetAlert2",
      "Api",
    ],
  },
  {
    id: 5,
    title: "Tuwebcuantica.com",
    description: "Landing page para venta de servicios personalizados de software y desarrollo web.",
    images: [
      "/projects/tuwebcuantica/main.png",
      "/projects/tuwebcuantica/services.png",
      "/projects/tuwebcuantica/techs.png",
      "/projects/tuwebcuantica/contact.png",
    ],
    demo: "",
    github: "https://github.com/nicog33b/tuwebcuantica-nextjs-tailwind-landing",
    tags: [
      "Next.js",
      "React",
      "EmailJS",
      "FramerMotion",
      "Nodemailer",
      "React Icons",
      "React Slick",
      "Slick Carousel",
      "SweetAlert2",
      "Tailwind CSS",
    ],
  },
  {
    id: 6,
    title: "Ambar Vestidos",
    description: "Plataforma para el alquiler de vestidos de fiesta con un diseño atractivo.",
    images: [
      "/projects/ambar/main.png",
      "/projects/ambar/contact.png",
      "/projects/ambar/rentup.png",
      "/projects/ambar/detail.png",
    ],
    demo: "",
    github: "https://github.com/nicog33b/employee-managment-backend",
    tags: [
      "React",
      "Next.js",
      "Heroicons",
      "Google Maps API",
      "AOS",
      "JavaScript"
    ],
  },
  {
    id: 7,
    title: "E-commerce JAP",
    description: "Proyecto e-commerce sin frameworks para demostrar habilidades en desarrollo web.",
    images: [
      "/projects/ecommerce-jap/main.png",
      "/projects/ecommerce-jap/login.png",
      "/projects/ecommerce-jap/categories.png",
    ],
    demo: "",
    github: "https://github.com/nicog33b/ecommerce-finalproject-vanilla",
    tags: ["JavaScript", "API", "HTML", "CSS"],
  },
];
